# Fitting a Bernoulli GLM with a single continuous predictor
mod1 <- glm(Survived ~ Fare, data = titanic, family = binomial(link = "logit"))

# Calling summary() on the fitted model
summary(mod1)

# Accessing key components of the model object
## Pulling out the beta coefficients

coefficients(mod1) # by calling the coefficients() on the model object
mod1$coefficients # by directly calling the coefficients vector from the
                  # model object list using the "$" syntax
mod1[["coefficients"]] # using the double bracket indexing

## Indexing the summary() object to get standard errors
sum_obj <- summary(mod1)
sum_obj$coefficients[, 2] # the second column from the coefficients table

## Accessing model residuals
residuals(mod1) # by default gives the deviance residuals
residuals(mod1, type = "response") # y - fitted values
mod1$residuals # notice that these residuals are different from those
               # generated by the residuals() function
mod1[["residuals"]]

## Accessing model predictions (predicted p)
fitted.values(mod1)
mod1$fitted.values
mod1[["fitted.values"]]

## Calling the values of the linear predictor
mod1$linear.predictors
mod1[["linear.predictors"]]
invlogit(mod1$linear.predictors) # equal to the fitted values

# Plotting a logistic model
plot(Survived ~ Fare, data = titanic)
lines(x = titanic$Fare, y = mod1$fitted.values) # oh no, what did we do wrong?!

## Let's create a separate data frame that we can sort by the predictor
plot_df <- data.frame(Fare = titanic$Fare, Preds = mod1$fitted.values)
plot_df <- plot_df[order(plot_df$Fare), ]

## Plotting with ordered data
plot(Survived ~ Fare, data = titanic)
lines(x = plot_df$Fare, y = plot_df$Preds)

## Using the model to predict at a higher resolution than the observed data
plot_df <- data.frame(Fare = seq(min(titanic$Fare), max(titanic$Fare), 1))
plot_df$Preds <- predict(mod1, newdata = plot_df, type = "response")

plot(Survived ~ Fare, data = titanic)
lines(x = plot_df$Fare, y = plot_df$Preds)

# Fitting a model with a single categorical predictor
mod2 <- glm(Survived ~ Sex, data = titanic, family = binomial(link = "logit"))
summary(mod2)
model.matrix(Survived ~ Sex, data = titanic)

# Fitting a model with both a continuous and categorical predictor
mod3 <- glm(Survived ~ Sex + Fare, data = titanic,
            family = binomial(link = "logit"))
summary(mod3)

# Fitting a model with two categorical predictors
titanic$Pclass <- factor(titanic$Pclass, levels = c("1", "2", "3"))
mod4 <- glm(Survived ~ Sex + Pclass, data = titanic,
            family = binomial(link = "logit"))
summary(mod4)
model.matrix(Survived ~ Sex + Pclass, data = titanic)

# Fitting an interaction model
mod5 <- glm(Survived ~ Sex*Fare, data = titanic,
            family = binomial(link = "logit"))
summary(mod5)
model.matrix(Survived ~ Sex*Fare, data = titanic)



